import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vercel Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Avatar</h1>

        <div style={{ display: 'flex', gap: 10 }}>
          <img
            className={styles.avatar}
            src="/vercel.svg?text=VC"
            alt="Vercel"
          />
          <img className={styles.avatar} src="/1" alt="ID 1" />
          <img className={styles.avatar} src="/satori" alt="Satori" />
          <img className={styles.avatar} src="/next.js" alt="Next.js" />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
